name: Maven Unit Tests
description: Run unit tests for Java apps

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: adopt
        cache: maven

    - name: Run Unit tests Tests
      shell: bash
      working-directory: back/user-ms
      run: mvn test
