name: aws-deploy
description: Deploy infrastructure to AWS using terraform
inputs:
  aws_deployment_role:
    required: true
    description: The deployment role to assume

runs:
  using: composite
  steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4        
        with:
          role-to-assume: ${{inputs.aws_deployment_role}}
          role-session-name: github-to-aws-via-oidc
          aws-region: eu-west-1
          role-skip-session-tagging: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3        
        with:
          terraform_version: "1.10.3"

      - name: Terraform Init
        working-directory: terraform
        shell: bash
        id: terraform-init
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        shell: bash
        id: terraform-validate
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        shell: bash
        id: terraform-plan
        run: terraform plan -lock=false
      
      - name: Terraform Apply
        working-directory: terraform
        shell: bash
        id: terraform-apply
        run: terraform apply -auto-approve -lock=false