name: General Checks - CI

on: 
    push:
        branches: 
            - 'main'

jobs:
    actions-lint:
        name: GitHub Actions Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4        
            - name: Lint Github Action files
              uses: docker://rhysd/actionlint:latest
              with:
                args: -color

              