name: Pull Request - CI

on: 
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'session_management/**'
      - 'back/user-ms/**'
      - 'terraform/**'
      - '.github/**'

env:
  PYTHON_VERSION: "3.13"

permissions:
  id-token: write
  contents: read
  
jobs:
  session-build:
      runs-on: ubuntu-latest
      name: Session -  Install dependencies and run unit tests
      steps:
        - uses: actions/checkout@v4

        - name: Python unit + integration tests
          uses: ./.github/actions/python-build
          with:
            python_version: ${{env.PYTHON_VERSION}}


  users-unit-tests:
    runs-on: ubuntu-latest
    name: User - run unit tests
    steps:
      - uses: actions/checkout@v4
                          
      - name: Java unit tests
        uses: ./.github/actions/maven-unit-tests
        
  users-integration-tests:
    runs-on: ubuntu-latest
    name: User - run integration tests
    steps:
      - uses: actions/checkout@v4
                          
      - name: Java integration tests
        uses: ./.github/actions/maven-integration-tests

  terraform-ci:
    runs-on: ubuntu-latest
    name: Terraform CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Terraform
        uses: ./.github/actions/terraform-ci
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_deployment_role: ${{secrets.AWS_DEPLOYMENT_ROLE_ARN}}