name: Session Management - CI

on: 
    push:
        branches: 
            - 'main'
        paths:
            - 'session_management/**'

env:
  PYTHON_VERSION: "3.13"            
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: $PYTHON_VERSION

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pwd
                ls session_management
                pip install -r ./session_management/requirements.txt

            - name: Run unit tests    
              run: |
                pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: ${{ always() }}
              with:
                name: pytest-results
                path: junit/test-results.xml
    
    docker:
      runs-on: ubuntu-latest
      needs:
        - build
      name: Generate and Publish Docker Image
      steps:
        - uses: actions/checkout@v4

        - name: Build And Publish
          shell: bash
          run: |
            DOCKER_REPO=${{secrets.SESSION_MANAGEMENT_DOCKER_REPO}}
            echo "DOCKER_REPO=${DOCKER_REPO}" >> $GITHUB_ENV
        
        - name: Docker Build
          shell: bash
          run: |
            docker build --no-cache -t iamind/session_management:latest ./session_management
            echo "DOCKER_REPO=${DOCKER_REPO}" >> $GITHUB_ENV
        
        - name: Docker Publish
          env:
            DOCKER_REPO_TOKEN: ${{secrets.DOCKER_REPO_TOKEN}}
            DOCKER_REPO_USER: ${{secrets.DOCKER_REPO_USER}}
          shell: bash
          run: |
            echo $DOCKER_REPO_TOKEN | docker login -u $DOCKER_REPO_USER --password-stdin docker.com
            docker push ${DOCKER_REPO} -a


      


