name: Session Analytics - CI

on: 
    pull_request:
        branches: 
            - 'main'
jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world"
