name: Terraform destroy Infrastructure

on:
    workflow_dispatch:


permissions:
    id-token: write
    contents: read

jobs:
    unlock_terraform_state:
        runs-on: ubuntu-latest
        name: Unlock Terraform state
        env:
            TF_INPUT: 0      
            TF_VAR_session_management_docker_image: brunogino/iamind-session_management
            TF_VAR_user_ms_docker_image: brunogino/iamind-user-ms
            TF_VAR_docker_hub_token: ${{secrets.DOCKER_REPO_TOKEN}}
            TF_VAR_docker_hub_user: ${{secrets.DOCKER_REPO_USER}}
            TF_VAR_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
        steps:
            - uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.AWS_DEPLOYMENT_ROLE_ARN}}
                role-session-name: github-to-aws-via-oidc
                aws-region: 'eu-west-1'
                role-skip-session-tagging: true

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.3"

            - name: Terraform Init
              id: terraform-init
              shell: bash
              working-directory: terraform
              run: terraform init
            
            - name: Terraform Plan
              id: terraform-plan
              shell: bash
              run: terraform plan -destroy

            - name: Terraform Destroy
              id: terraform-destroy
              shell: bash
              working-directory: terraform
              run: terraform apply -destroy -auto-approve

      
